//! Carry an arbitrary document across a version boundary.
//!
//! This is the hub's path: bytes plus the endpoint they arrived on, with no guarantee that the
//! bytes are the object the endpoint claims. One of the crate's panic-freedom properties covers
//! the same ground with generated values; this one uses generated bytes.
#![no_main]

use libfuzzer_sys::fuzz_target;
use ocpi_kit::VersionNumber;
use ocpi_kit::convert::wire::ObjectKind;

const KINDS: &[ObjectKind] = &[
    ObjectKind::Location,
    ObjectKind::Evse,
    ObjectKind::Connector,
    ObjectKind::Session,
    ObjectKind::Cdr,
    ObjectKind::Tariff,
    ObjectKind::Token,
    ObjectKind::AuthorizationInfo,
    ObjectKind::Credentials,
    ObjectKind::ClientInfo,
    ObjectKind::StartSession,
    ObjectKind::ReserveNow,
];

fuzz_target!(|data: &[u8]| {
    let Ok(value) = serde_json::from_slice::<serde_json::Value>(data) else { return };
    for kind in KINDS {
        let up = kind.bridge(&VersionNumber::V2_2_1, &VersionNumber::V2_3_0, value.clone());
        let down = kind.bridge(&VersionNumber::V2_3_0, &VersionNumber::V2_2_1, value.clone());
        for converted in [up, down].into_iter().flatten() {
            let _ = converted.lossy.to_status_message();
            let _ = serde_json::to_string(&converted.value);
        }
        // A merge patch crosses by inspection rather than conversion.
        let fields: Vec<&str> =
            value.as_object().map(|o| o.keys().map(String::as_str).collect()).unwrap_or_default();
        let _ = kind.patch_crosses_unchanged(&fields);
    }
});
